"""Caddy reverse proxy provider — built-in IngressProvider implementation."""

import os
import sys

from dekube import IngressProvider, write_secret_files  # pylint: disable=import-error  # h2c resolves at runtime


class CaddyProvider(IngressProvider):
    """Convert Ingress manifests to a Caddy service + Caddyfile."""
    name = "caddy"

    def build_service(self, entries, ctx):
        """Build the Caddy compose service dict."""
        # Extension config with fallback to top-level caddy_* keys for retrocompat
        ext_cfg = ctx.extension_config
        if ext_cfg.get("disabled"):
            return {}

        volume_root = ctx.config.get("volume_root", "./data")
        caddy_volumes = [
            "./Caddyfile:/etc/caddy/Caddyfile:ro",
            f"{volume_root}/caddy:/data",
            f"{volume_root}/caddy-config:/config",
        ]
        # Mount CA secrets referenced by server-ca annotations. Nothing else in the
        # pipeline volume-mounts these (they're only referenced by annotation), so we
        # have to write them to disk ourselves — and resolve the real cert filename
        # instead of assuming "ca.crt" (fixes both: missing dir + wrong filename).
        ca_files = self._resolve_ca_secrets(entries, ctx)
        for secret_name in sorted(ca_files):
            caddy_volumes.append(
                f"./secrets/{secret_name}"
                f":/etc/caddy/certs/{secret_name}:ro")
        return {"caddy": {
            "image": "caddy:2-alpine", "restart": "always",
            "ports": ["80:80", "443:443"],
            "volumes": caddy_volumes,
        }}

    @staticmethod
    def _resolve_ca_secrets(entries, ctx):
        """Write each server-ca Secret to disk and resolve its actual cert filename.

        Stashes the resolved filename onto each matching entry (as `_server_ca_file`)
        for write_config() to use later — it doesn't receive ctx. Returns the set of
        secret names successfully written.
        """
        ca_secret_names = {e["server_ca_secret"] for e in entries
                            if e.get("server_ca_secret")}
        ca_files = {}
        for secret_name in ca_secret_names:
            if write_secret_files(secret_name, ctx) is None:
                continue  # not found — ctx.warnings already has the reason
            secret = ctx.secrets.get(secret_name) or {}
            keys = list((secret.get("data") or {})) + list((secret.get("stringData") or {}))
            if "ca.crt" in keys:
                ca_files[secret_name] = "ca.crt"
            elif keys:
                ca_files[secret_name] = keys[0]
                ctx.warnings.append(
                    f"Secret '{secret_name}' referenced as server-ca has no 'ca.crt' "
                    f"key — using '{keys[0]}' instead")
            else:
                ca_files[secret_name] = "ca.crt"  # empty secret, keep the conventional name

        for e in entries:
            secret_name = e.get("server_ca_secret")
            if secret_name in ca_files:
                e["_server_ca_file"] = ca_files[secret_name]
        return ca_files

    def write_config(self, entries, output_dir, config):
        """Write the Caddyfile."""
        if not entries:
            return

        # Extension config with fallback to top-level caddy_* keys for retrocompat
        ext_cfg = (config.get("extensions") or {}).get(self.name) or {}
        caddy_email = ext_cfg.get("email")
        tls_internal = bool(ext_cfg.get("tls_internal"))

        filename = "Caddyfile"
        if config.get("disable_ingress"):
            project = config.get("name", "project")
            filename = f"Caddyfile-{project}"

        replacements = config.get("replacements") or []
        by_host: dict[str, list[dict]] = {}
        for e in entries:
            for r in replacements:
                if not r or not r.get("old"):
                    continue
                e["upstream"] = e["upstream"].replace(r["old"], r.get("new") or "")
            by_host.setdefault(e["host"], []).append(e)

        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write("# Generated by dekube — do not edit manually\n\n")
            if caddy_email:
                f.write(f"{{\n\temail {caddy_email}\n}}\n\n")
            for host, host_entries in by_host.items():
                self._write_caddy_host_block(f, host, host_entries, tls_internal)
        print(f"Wrote {path}", file=sys.stderr)

    @staticmethod
    def _write_caddy_reverse_proxy(f, entry: dict, indent: str = "\t") -> None:
        """Write a reverse_proxy directive, with TLS transport if upstream is HTTPS."""
        scheme = entry.get("scheme", "http")
        upstream = entry["upstream"]
        if scheme != "https":
            f.write(f"{indent}reverse_proxy {upstream}\n")
            return
        ca_secret = entry.get("server_ca_secret", "")
        f.write(f"{indent}reverse_proxy https://{upstream} {{\n")
        f.write(f"{indent}\ttransport http {{\n")
        if ca_secret:
            sni = entry.get("server_sni", "")
            if sni:
                f.write(f"{indent}\t\ttls_server_name {sni}\n")
            ca_file = entry.get("_server_ca_file", "ca.crt")
            f.write(f"{indent}\t\ttls_trust_pool file"
                    f" /etc/caddy/certs/{ca_secret}/{ca_file}\n")
        else:
            f.write(f"{indent}\t\ttls_insecure_skip_verify\n")
        f.write(f"{indent}\t}}\n")
        f.write(f"{indent}}}\n")

    @staticmethod
    def _write_caddy_directives(f, entry: dict, indent: str = "\t") -> None:
        """Write structured entry fields as Caddy directives."""
        # Structured fields: response_headers, max_body_size
        for hdr_name, hdr_val in (entry.get("response_headers") or {}).items():
            safe_val = str(hdr_val).replace('"', '\\"').replace('\n', ' ')
            f.write(f"{indent}header {hdr_name} \"{safe_val}\"\n")
        if entry.get("max_body_size"):
            f.write(f"{indent}request_body max_size {entry['max_body_size']}\n")
        # Fallback: raw extra_directives (deprecated, for third-party rewriter compat)
        for directive in entry.get("extra_directives") or []:
            f.write(f"{indent}{directive}\n")

    @staticmethod
    def _write_caddy_host_block(f, host: str, host_entries: list[dict],
                                tls_internal: bool = False) -> None:
        """Write a single Caddy host block (specific paths first, catch-all last)."""
        specific = [e for e in host_entries if e["path"] and e["path"] != "/"]
        catchall = [e for e in host_entries if not e["path"] or e["path"] == "/"]
        f.write(f"{host} {{\n")
        if tls_internal:
            f.write("\ttls internal\n")
        for entry in specific:
            f.write(f"\thandle {entry['path']}* {{\n")
            if entry.get("strip_prefix"):
                f.write(f"\t\turi strip_prefix {entry['strip_prefix']}\n")
            CaddyProvider._write_caddy_directives(f, entry, indent="\t\t")
            CaddyProvider._write_caddy_reverse_proxy(f, entry, indent="\t\t")
            f.write("\t}\n")
        for entry in catchall:
            CaddyProvider._write_caddy_directives(f, entry)
            CaddyProvider._write_caddy_reverse_proxy(f, entry)
        f.write("}\n\n")
